/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/character.glb -o src/components/Character.jsx -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";
import * as THREE from "three";

export function Character({ animation, ...props }) {
  const group = useRef();
  const { nodes, materials, animations, scene } = useGLTF(
    "/models/character.glb"
  );
  console.log(
    "Available animations:",
    animations.map((a) => a.name)
  );
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    const act = actions?.[animation];
    console.log(
      "Trying to play animation:",
      animation,
      "Action exists:",
      !!act
    );
    if (!act) return;
    act.reset().fadeIn(0.24).play();
    return () => act.fadeOut?.(0.24);
  }, [actions, animation]);
  return (
    <group ref={group} {...props} dispose={null}>
      {/* prefer rendering the original scene if present */}
      {scene ? (
        <primitive object={scene} />
      ) : (
        <group name="Scene">
          <group name="fall_guys">
            {nodes?._rootJoint && <primitive object={nodes._rootJoint} />}
            {/* render skinned meshes if material exists; otherwise render a visible debug mesh */}
            {nodes?.body?.geometry &&
              (materials?.Material ? (
                <skinnedMesh
                  name="body"
                  geometry={nodes.body.geometry}
                  material={materials.Material}
                  skeleton={nodes.body.skeleton}
                  castShadow
                  receiveShadow
                />
              ) : (
                <mesh geometry={nodes.body.geometry} castShadow receiveShadow>
                  <meshStandardMaterial
                    color={"#ff7f50"}
                    skinning={!!nodes.body.skeleton}
                  />
                </mesh>
              ))}
            {nodes?.eye?.geometry &&
              (materials?.Material ? (
                <skinnedMesh
                  name="eye"
                  geometry={nodes.eye.geometry}
                  material={materials.Material}
                  skeleton={nodes.eye.skeleton}
                  castShadow
                  receiveShadow
                />
              ) : (
                <mesh geometry={nodes.eye.geometry} castShadow receiveShadow>
                  <meshStandardMaterial color={"#ffffff"} />
                </mesh>
              ))}
            {nodes?.["hand-"]?.geometry &&
              (materials?.Material ? (
                <skinnedMesh
                  name="hand-"
                  geometry={nodes["hand-"].geometry}
                  material={materials.Material}
                  skeleton={nodes["hand-"].skeleton}
                  castShadow
                  receiveShadow
                />
              ) : (
                <mesh
                  geometry={nodes["hand-"].geometry}
                  castShadow
                  receiveShadow
                >
                  <meshStandardMaterial color={"#cccccc"} />
                </mesh>
              ))}
            {nodes?.leg?.geometry &&
              (materials?.Material ? (
                <skinnedMesh
                  name="leg"
                  geometry={nodes.leg.geometry}
                  material={materials.Material}
                  skeleton={nodes.leg.skeleton}
                  castShadow
                  receiveShadow
                />
              ) : (
                <mesh geometry={nodes.leg.geometry} castShadow receiveShadow>
                  <meshStandardMaterial color={"#999999"} />
                </mesh>
              ))}
          </group>
        </group>
      )}
    </group>
  );
}

useGLTF.preload("/models/character.glb");
