/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/comp.glb -o ./src/components/comp.jsx -r 
Author: BrushDip (https://sketchfab.com/BrushDip)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-computer-sketchfab-weekly-11-mar23-d9931a9aba7c4ea1bc12b2a59dcef16e
Title: 3d computer  - Sketchfab Weekly - 11 Mar'23
*/


import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useEffect } from 'react'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/comp.glb')
  const { actions } = useAnimations(animations, group)

    useEffect(() => {
      if (!actions) return
  
      Object.values(actions).forEach((action) => {
        action.reset().play()
      })
  
      return () => {
        Object.values(actions).forEach((action) => action.stop())
      }
    }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" rotation={[-Math.PI / 2, 0, -0.033]} scale={0.01}>
          <group name="Screen001" position={[5.658, 1.643, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen001_animation_0" geometry={nodes.Screen001_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen002" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen002_animation_0" geometry={nodes.Screen002_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen003" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen003_animation_0" geometry={nodes.Screen003_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen004" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen004_animation_0" geometry={nodes.Screen004_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen005" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen005_animation_0" geometry={nodes.Screen005_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen006" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen006_animation_0" geometry={nodes.Screen006_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen007" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen007_animation_0" geometry={nodes.Screen007_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen008" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen008_animation_0" geometry={nodes.Screen008_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen009" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen009_animation_0" geometry={nodes.Screen009_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen010" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen010_animation_0" geometry={nodes.Screen010_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen011" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen011_animation_0" geometry={nodes.Screen011_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen012" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen012_animation_0" geometry={nodes.Screen012_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen013" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen013_animation_0" geometry={nodes.Screen013_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen014" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen014_animation_0" geometry={nodes.Screen014_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen015" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen015_animation_0" geometry={nodes.Screen015_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen016" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen016_animation_0" geometry={nodes.Screen016_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen017" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen017_animation_0" geometry={nodes.Screen017_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen018" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen018_animation_0" geometry={nodes.Screen018_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen019" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen019_animation_0" geometry={nodes.Screen019_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen020" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen020_animation_0" geometry={nodes.Screen020_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen021" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen021_animation_0" geometry={nodes.Screen021_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Tower-light-007" position={[16.089, -3.47, -14.495]} rotation={[Math.PI / 2, 0, 0]} scale={0.963}>
            <group name="Object_256" position={[0, 0, -0.807]}>
              <mesh name="Tower-light-007_Material_#37_0" geometry={nodes['Tower-light-007_Material_#37_0'].geometry} material={materials.Material_37} />
            </group>
          </group>
          <group name="Tower-light-008" position={[15.155, -3.47, -14.495]} rotation={[Math.PI / 2, 0, 0]} scale={0.963}>
            <group name="Object_259" position={[0, 0, -0.807]}>
              <mesh name="Tower-light-008_Material_#37_0" geometry={nodes['Tower-light-008_Material_#37_0'].geometry} material={materials.Material_37} />
            </group>
          </group>
          <group name="Screen022" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen022_animation_0" geometry={nodes.Screen022_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen023" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen023_animation_0" geometry={nodes.Screen023_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen024" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen024_animation_0" geometry={nodes.Screen024_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen025" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen025_animation_0" geometry={nodes.Screen025_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen026" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen026_animation_0" geometry={nodes.Screen026_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen027" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen027_animation_0" geometry={nodes.Screen027_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen028" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen028_animation_0" geometry={nodes.Screen028_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen029" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen029_animation_0" geometry={nodes.Screen029_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen030" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen030_animation_0" geometry={nodes.Screen030_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen031" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen031_animation_0" geometry={nodes.Screen031_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen032" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen032_animation_0" geometry={nodes.Screen032_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen033" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen033_animation_0" geometry={nodes.Screen033_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen034" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen034_animation_0" geometry={nodes.Screen034_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen035" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen035_animation_0" geometry={nodes.Screen035_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen036" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen036_animation_0" geometry={nodes.Screen036_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen037" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen037_animation_0" geometry={nodes.Screen037_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen038" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen038_animation_0" geometry={nodes.Screen038_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen039" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen039_animation_0" geometry={nodes.Screen039_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen040" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen040_animation_0" geometry={nodes.Screen040_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen041" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen041_animation_0" geometry={nodes.Screen041_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen042" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen042_animation_0" geometry={nodes.Screen042_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen043" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen043_animation_0" geometry={nodes.Screen043_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen044" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen044_animation_0" geometry={nodes.Screen044_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen045" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen045_animation_0" geometry={nodes.Screen045_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen046" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen046_animation_0" geometry={nodes.Screen046_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen047" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen047_animation_0" geometry={nodes.Screen047_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen048" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen048_animation_0" geometry={nodes.Screen048_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen049" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen049_animation_0" geometry={nodes.Screen049_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen050" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen050_animation_0" geometry={nodes.Screen050_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen051" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen051_animation_0" geometry={nodes.Screen051_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen052" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen052_animation_0" geometry={nodes.Screen052_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen053" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen053_animation_0" geometry={nodes.Screen053_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen054" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen054_animation_0" geometry={nodes.Screen054_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen055" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen055_animation_0" geometry={nodes.Screen055_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen056" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen056_animation_0" geometry={nodes.Screen056_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen057" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen057_animation_0" geometry={nodes.Screen057_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen058" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen058_animation_0" geometry={nodes.Screen058_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen059" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen059_animation_0" geometry={nodes.Screen059_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen060" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen060_animation_0" geometry={nodes.Screen060_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen061" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen061_animation_0" geometry={nodes.Screen061_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen062" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen062_animation_0" geometry={nodes.Screen062_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen063" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen063_animation_0" geometry={nodes.Screen063_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen064" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen064_animation_0" geometry={nodes.Screen064_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen065" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen065_animation_0" geometry={nodes.Screen065_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen066" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen066_animation_0" geometry={nodes.Screen066_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen067" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen067_animation_0" geometry={nodes.Screen067_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen068" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen068_animation_0" geometry={nodes.Screen068_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen069" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen069_animation_0" geometry={nodes.Screen069_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen070" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen070_animation_0" geometry={nodes.Screen070_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen071" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen071_animation_0" geometry={nodes.Screen071_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen072" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen072_animation_0" geometry={nodes.Screen072_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen073" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen073_animation_0" geometry={nodes.Screen073_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen074" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen074_animation_0" geometry={nodes.Screen074_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen075" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen075_animation_0" geometry={nodes.Screen075_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen076" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen076_animation_0" geometry={nodes.Screen076_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen077" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen077_animation_0" geometry={nodes.Screen077_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen078" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen078_animation_0" geometry={nodes.Screen078_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen079" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen079_animation_0" geometry={nodes.Screen079_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen080" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen080_animation_0" geometry={nodes.Screen080_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen081" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen081_animation_0" geometry={nodes.Screen081_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen082" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen082_animation_0" geometry={nodes.Screen082_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen083" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen083_animation_0" geometry={nodes.Screen083_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen084" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen084_animation_0" geometry={nodes.Screen084_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen085" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen085_animation_0" geometry={nodes.Screen085_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen086" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen086_animation_0" geometry={nodes.Screen086_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen087" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen087_animation_0" geometry={nodes.Screen087_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen088" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen088_animation_0" geometry={nodes.Screen088_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen089" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen089_animation_0" geometry={nodes.Screen089_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen090" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen090_animation_0" geometry={nodes.Screen090_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen091" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen091_animation_0" geometry={nodes.Screen091_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen092" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen092_animation_0" geometry={nodes.Screen092_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen093" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen093_animation_0" geometry={nodes.Screen093_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen094" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen094_animation_0" geometry={nodes.Screen094_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen095" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen095_animation_0" geometry={nodes.Screen095_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen096" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen096_animation_0" geometry={nodes.Screen096_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen097" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen097_animation_0" geometry={nodes.Screen097_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen098" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen098_animation_0" geometry={nodes.Screen098_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen099" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen099_animation_0" geometry={nodes.Screen099_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen100" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen100_animation_0" geometry={nodes.Screen100_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen101" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen101_animation_0" geometry={nodes.Screen101_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen102" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen102_animation_0" geometry={nodes.Screen102_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen103" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen103_animation_0" geometry={nodes.Screen103_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen104" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen104_animation_0" geometry={nodes.Screen104_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen105" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen105_animation_0" geometry={nodes.Screen105_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen106" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen106_animation_0" geometry={nodes.Screen106_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen107" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen107_animation_0" geometry={nodes.Screen107_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen108" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen108_animation_0" geometry={nodes.Screen108_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen109" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen109_animation_0" geometry={nodes.Screen109_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen110" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen110_animation_0" geometry={nodes.Screen110_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen111" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen111_animation_0" geometry={nodes.Screen111_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen112" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen112_animation_0" geometry={nodes.Screen112_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen113" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen113_animation_0" geometry={nodes.Screen113_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen114" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen114_animation_0" geometry={nodes.Screen114_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen115" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen115_animation_0" geometry={nodes.Screen115_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen116" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen116_animation_0" geometry={nodes.Screen116_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen117" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen117_animation_0" geometry={nodes.Screen117_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen118" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen118_animation_0" geometry={nodes.Screen118_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen119" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen119_animation_0" geometry={nodes.Screen119_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen120" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen120_animation_0" geometry={nodes.Screen120_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen121" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen121_animation_0" geometry={nodes.Screen121_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen122" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen122_animation_0" geometry={nodes.Screen122_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen123" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen123_animation_0" geometry={nodes.Screen123_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen124" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen124_animation_0" geometry={nodes.Screen124_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen125" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen125_animation_0" geometry={nodes.Screen125_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen126" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen126_animation_0" geometry={nodes.Screen126_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen127" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen127_animation_0" geometry={nodes.Screen127_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen128" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen128_animation_0" geometry={nodes.Screen128_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen129" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen129_animation_0" geometry={nodes.Screen129_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen130" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen130_animation_0" geometry={nodes.Screen130_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen131" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen131_animation_0" geometry={nodes.Screen131_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen132" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen132_animation_0" geometry={nodes.Screen132_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen133" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen133_animation_0" geometry={nodes.Screen133_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen134" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen134_animation_0" geometry={nodes.Screen134_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen135" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen135_animation_0" geometry={nodes.Screen135_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen136" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen136_animation_0" geometry={nodes.Screen136_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen137" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen137_animation_0" geometry={nodes.Screen137_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen138" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen138_animation_0" geometry={nodes.Screen138_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen139" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen139_animation_0" geometry={nodes.Screen139_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen140" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen140_animation_0" geometry={nodes.Screen140_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen141" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen141_animation_0" geometry={nodes.Screen141_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen142" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen142_animation_0" geometry={nodes.Screen142_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen143" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen143_animation_0" geometry={nodes.Screen143_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen144" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen144_animation_0" geometry={nodes.Screen144_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen145" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen145_animation_0" geometry={nodes.Screen145_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen146" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen146_animation_0" geometry={nodes.Screen146_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen147" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen147_animation_0" geometry={nodes.Screen147_animation_0.geometry} material={materials.animation} />
          </group>
          <group name="Screen148" position={[5.658, 1.644, 0.812]} rotation={[Math.PI / 2, 0, 0]} scale={[0.923, 0.855, 0.855]}>
            <mesh name="Screen148_animation_0" geometry={nodes.Screen148_animation_0.geometry} material={materials.animation} />
          </group>
        </group>
        <mesh name="Monitor-A-_computer_0" geometry={nodes['Monitor-A-_computer_0'].geometry} material={materials.computer} position={[0.059, 0.009, 0.015]} rotation={[0, -0.033, 0]} scale={[0.009, 0.01, 0.009]} />
        <mesh name="screen_glass_screen_0" geometry={nodes.screen_glass_screen_0.geometry} material={materials.screen} position={[0.059, 0.009, 0.002]} rotation={[-Math.PI / 2, 0, -0.033]} scale={[0.009, 0.01, 0.01]} />
        <mesh name="base__0" geometry={nodes.base__0.geometry} material={materials.base__0} position={[0.088, -0.214, -0.11]} rotation={[-Math.PI / 2, 0, -0.033]} scale={[0.01, 0.011, 0.01]} />
        <mesh name="key030_Material_#36_0" geometry={nodes['key030_Material_#36_0'].geometry} material={materials.Material_36} position={[-0.082, -0.199, 0.147]} rotation={[-1.391, -0.006, -0.032]} scale={0.015} />
        <mesh name="key032_Material_#35_0" geometry={nodes['key032_Material_#35_0'].geometry} material={materials.Material_35} position={[-0.08, -0.19, 0.102]} rotation={[-1.391, -0.006, -0.032]} scale={0.015} />
        <mesh name="key033_Material_#34_0" geometry={nodes['key033_Material_#34_0'].geometry} material={materials.Material_34} position={[0.182, -0.186, 0.087]} rotation={[-1.391, -0.006, -0.032]} scale={0.015} />
        <mesh name="key034_keys_0" geometry={nodes.key034_keys_0.geometry} material={materials.keys} position={[0.182, -0.19, 0.111]} rotation={[-1.391, -0.006, -0.032]} scale={0.015} />
        <mesh name="key037_keys2_0" geometry={nodes.key037_keys2_0.geometry} material={materials.keys2} position={[0.205, -0.186, 0.088]} rotation={[-1.391, -0.006, -0.032]} scale={0.015} />
        <mesh name="Screen149_animation_0" geometry={nodes.Screen149_animation_0.geometry} material={materials.animation} position={[0.057, 0.008, -0.015]} rotation={[0, -0.033, 0]} scale={0.009} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/comp.glb')
