/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/flying_saucer.glb -o ./src/components/flying_saucer.jsx -r /models 
Author: rayleighsyafiq (https://sketchfab.com/rayleighsyafiq)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flying-saucer-73a18e8932d74a97920d92467d66b1a8
Title: Flying Saucer
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useEffect } from 'react'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/flying_saucer.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
      useEffect(() => {
        if (!actions) return
        
        const action = actions["abduction_rings"];
        if(!action) return;

        action.reset();
        action.timeScale = 0.5;
        action.play();
    
        return () => {
          action.stop();
        }
      }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.material_0} skeleton={nodes.Object_17.skeleton} scale={0.02} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/flying_saucer.glb')
